(() => {
'use strict';
if(window.parent===window){location.replace('/#concert');return;}
const $ = id => document.getElementById(id);
let job = null, rows = [], timer = null, auditionEnd = null, dirty = false, busy = false, loading = false, activeBoundary = null, draggingBoundary = false;
const fmt = s => {const ms=Math.round(s*1000);return [Math.floor(ms/3600000),Math.floor(ms/60000)%60,Math.floor(ms/1000)%60].map(v=>String(v).padStart(2,'0')).join(':')+'.'+String(ms%1000).padStart(3,'0');};
function parse(s){const p=s.trim().split(':');if(p.length>3||p.some(v=>!/^\d+(\.\d+)?$/.test(v)))throw Error('时间请填写 HH:MM:SS.sss 或秒数');const n=p.reduce((a,v)=>a*60+Number(v),0);if(!Number.isFinite(n))throw Error('无效时间');return n;}
function fail(e){$('error').textContent=e.message||String(e);}
async function api(path,data){const url='/api/concert/'+path;const r=await fetch(url,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const contentType=r.headers.get('content-type')||'';const text=await r.text();let d=null;try{if(contentType.includes('json'))d=JSON.parse(text);}catch(_){d=null;}if(!d)throw Error(`接口返回了非 JSON（${r.status} ${r.statusText}）：${url}`);if(!r.ok)throw Error(d.error||`请求失败（${r.status}）`);return d;}
function controls(){const blocked=busy||loading;for(const id of ['analyze','newAnalysis','reanalyze','refresh'])$(id).disabled=blocked;for(const id of ['save','export','split','snap','merge'])$(id).disabled=blocked||!rows.length;$('cancel').hidden=!busy;$('version').disabled=blocked||!(job?.analysis_versions?.length);if(blocked)draggingBoundary=false;$('downloads').querySelectorAll('button').forEach(b=>b.disabled=blocked);$('history').querySelectorAll('button').forEach(b=>b.disabled=blocked);$('segments').querySelectorAll('input,button').forEach(b=>b.disabled=blocked);}
function validate(){const invalid=$('segments').querySelector('input:invalid');if(invalid){invalid.reportValidity();throw Error('请先修正无效时间');}let prev=0;for(const [i,s] of rows.entries()){if(!Number.isFinite(s.start)||!Number.isFinite(s.end)||s.start<0||s.end>job.duration+.05||s.end-s.start<.2||s.start<prev-.001)throw Error(`第 ${i+1} 段的时间无效或与上一段重叠，请先修正`);prev=s.end;}return rows;}
function mark(){dirty=true;$('save').textContent='保存调整 *';$('manifest').textContent='下载已保存时间表';draw();}
function seek(s,play=false,end=null){const p=$('player');auditionEnd=end;p.currentTime=Math.max(0,Math.min(job?.duration||0,s));if(play)p.play().catch(fail);}
function syncTableTimes(){const trs=[...$('segments').querySelectorAll('tr')];rows.forEach((s,i)=>{const inputs=trs[i]?.querySelectorAll('input.time');if(inputs?.length===2){inputs[0].value=fmt(s.start);inputs[1].value=fmt(s.end);}});}
function canvasTime(event){const rect=$('waveform').getBoundingClientRect();return Math.max(0,Math.min(job?.duration||0,(event.clientX-rect.left)/rect.width*(job?.duration||0)));}
function boundaryAt(clientX){if(!job||rows.length<2)return null;const rect=$('waveform').getBoundingClientRect();const x=clientX-rect.left;let nearest=null,distance=Infinity;rows.slice(1).forEach((s,i)=>{const d=Math.abs(s.start/job.duration*rect.width-x);if(d<distance){distance=d;nearest=i+1;}});return distance<=12?nearest:null;}
function setBoundary(index,time){if(index===null||index<1||index>=rows.length)return;const min=rows[index-1].start+.2,max=rows[index].end-.2;const value=Math.max(min,Math.min(max,Math.round(time*1000)/1000));rows[index-1].end=value;rows[index].start=value;activeBoundary=index;syncTableTimes();mark();}
function mergeBoundary(index){if(index===null||index<1||index>=rows.length)return;rows[index-1].end=rows[index].end;rows[index-1].selected=rows[index-1].selected||rows[index].selected;rows.splice(index,1);activeBoundary=null;mark();renderRows();}
function mergeCurrentBoundary(){let index=activeBoundary;if(index===null&&job&&rows.length>1){const now=$('player').currentTime;let distance=Infinity;rows.slice(1).forEach((s,i)=>{const d=Math.abs(s.start-now);if(d<distance){distance=d;index=i+1;}});if(distance>10)index=null;}if(index===null)return fail(Error('请先点击或拖动一个边界，或把播放位置移到边界附近'));mergeBoundary(index);}
function snapCurrentBoundary(){if(!job||rows.length<2)return fail(Error('至少需要两个片段才能吸附切割边界'));const now=$('player').currentTime;let index=null,distance=Infinity;rows.slice(1).forEach((s,i)=>{const d=Math.abs(s.start-now);if(d<distance){distance=d;index=i+1;}});if(index===null)return fail(Error('没有可吸附的内部切割边界'));$('error').textContent='';setBoundary(index,now);}
function trimSpeechEdge(index,edge,time){const s=rows[index],t=Number(time);if(!s||!Number.isFinite(t)||t<=s.start+.2||t>=s.end-.2)throw Error('讲话边界与片段边界过近，无法安全调整');if(edge==='start'&&index>0&&rows[index-1].end>t+.001)throw Error('调整后会与上一段重叠，请先试听并手动调整');if(edge==='end'&&index+1<rows.length&&rows[index+1].start<t-.001)throw Error('调整后会与下一段重叠，请先试听并手动调整');s[edge]=Math.round(t*1000)/1000;mark();renderRows();}
function renderSpeechReview(){const ranges=job?.speech_ranges||[],panel=$('speechReview'),root=$('speechRanges');panel.hidden=!ranges.length;root.replaceChildren();$('speechSummary').textContent=`疑似讲话区间 · ${ranges.length} 段`;ranges.forEach((range,i)=>{const item=document.createElement('div');item.className='speechRangeItem';const label=document.createElement('span');label.textContent=`${String(i+1).padStart(2,'0')}　${fmt(range.start)} – ${fmt(range.end)}　分类分：讲话 ${Number(range.speech_score??range.score??0).toFixed(2)} / 音乐 ${Number(range.music_score??0).toFixed(2)}`;const listen=document.createElement('button');listen.textContent='试听前后';listen.onclick=()=>seek(Math.max(0,range.start-3),true,Math.min(job.duration,range.end+3));item.append(label,listen);root.append(item);});}
function renderRows(){const body=$('segments');if(activeBoundary!==null&&activeBoundary>=rows.length)activeBoundary=null;body.replaceChildren();$('count').textContent=rows.length?`· ${rows.length} 段`:'';if(!rows.length){const tr=body.insertRow();const td=tr.insertCell();td.colSpan=5;td.className='empty';td.textContent='分析完成后，候选分段会显示在这里';}
rows.forEach((s,i)=>{const tr=body.insertRow();let td=tr.insertCell();const check=document.createElement('input');check.type='checkbox';check.checked=s.selected;check.setAttribute('aria-label',`导出第 ${i+1} 段`);check.onchange=()=>{s.selected=check.checked;mark();};td.append(check);
td=tr.insertCell();const title=document.createElement('input');title.type='text';title.value=s.title;title.setAttribute('aria-label',`第 ${i+1} 段名称`);title.oninput=()=>{s.title=title.value;mark();};td.append(title);const speech=(job.speech_ranges||[]).filter(r=>r.start<s.end&&r.end>s.start);if(speech.length){const flag=document.createElement('span');flag.className='speechFlag';flag.textContent=`含 ${speech.length} 段疑似讲话`;td.append(flag);}
for(const key of ['start','end']){td=tr.insertCell();const input=document.createElement('input');input.type='text';input.className='time';input.value=fmt(s[key]);input.setAttribute('aria-label',`第 ${i+1} 段${key==='start'?'开始':'结束'}时间`);input.oninput=()=>{mark();try{const old=s[key],n=parse(input.value);s[key]=n;const ni=key==='start'?i-1:i+1,neighbor=rows[ni],other=key==='start'?'end':'start';if(neighbor&&Math.abs(neighbor[other]-old)<.001){neighbor[other]=n;body.rows[ni].querySelectorAll('input.time')[other==='start'?0:1].value=fmt(n);}input.setCustomValidity('');draw();}catch(e){input.setCustomValidity(e.message);}};input.onchange=()=>{if(input.checkValidity())input.value=fmt(s[key]);else input.reportValidity();};td.append(input);}
td=tr.insertCell();const button=(label,fn,extraClass='')=>{const b=document.createElement('button');b.textContent=label;b.className=extraClass;b.onclick=()=>{try{fn();}catch(e){fail(e);}};td.append(b);};button('试听起点',()=>seek(s.start,true,Math.min(job.duration,s.start+8)));button('试听终点',()=>seek(s.end-8,true,Math.min(job.duration,s.end+8)));button('播放本段',()=>seek(s.start,true,s.end));const lead=(job.speech_ranges||[]).find(r=>r.start<=s.start+8&&r.end>s.start+.2&&r.end<s.end-.2);if(lead)button('起点移到候选后',()=>trimSpeechEdge(i,'start',lead.end),'speechCut');const tail=(job.speech_ranges||[]).find(r=>r.end>=s.end-8&&r.start>s.start+.2&&r.start<s.end-.2);if(tail)button('结束移到候选前',()=>trimSpeechEdge(i,'end',tail.start),'speechCut');if(i<rows.length-1)button('合并下一段',()=>{s.end=rows[i+1].end;rows.splice(i+1,1);mark();renderRows();});});controls();draw();}
function draw(){
  const c=$('waveform'),ctx=c.getContext('2d'),ratio=window.devicePixelRatio||1,w=Math.max(300,c.clientWidth);
  c.width=w*ratio;c.height=90*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,w,90);
  if(!job?.waveform)return;
  ctx.fillStyle='#254b76';const wave=job.waveform;
  wave.forEach(p=>{const x=p.time/job.duration*w,h=Math.max(2,Math.min(70,(p.db+65)/65*70));ctx.fillRect(x,82-h,Math.max(1,w/wave.length),h);});
  ctx.fillStyle='rgba(240,136,62,.20)';(job.speech_ranges||[]).forEach(r=>{const x=Math.max(0,r.start/job.duration*w),end=Math.min(w,r.end/job.duration*w);ctx.fillRect(x,0,Math.max(2,end-x),90);});
  rows.slice(1).forEach((s,i)=>{const x=s.start/job.duration*w;ctx.strokeStyle=(i+1===activeBoundary)?'#f0883e':'#58a6ff';ctx.lineWidth=(i+1===activeBoundary)?3:1;ctx.beginPath();ctx.moveTo(x,3);ctx.lineTo(x,87);ctx.stroke();ctx.fillStyle=(i+1===activeBoundary)?'#f0883e':'#58a6ff';ctx.fillRect(x-4,3,8,8);});
  ctx.strokeStyle='#ffd24a';ctx.lineWidth=1;const x=$('player').currentTime/job.duration*w;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,90);ctx.stroke();
}
function exportsUI(){const root=$('downloads');root.replaceChildren();for(const ex of [...(job?.exports||[])].reverse()){const section=document.createElement('section'),p=document.createElement('p');p.className='hint';p.textContent=`${ex.state&&ex.state!=='done'?'未完成批次 · ':''}已导出 ${ex.files.length} 段 · ${ex.mode==='copy'?'快速模式':'精确模式'} · ${ex.path}`;section.append(p);if(['cancelled','error','interrupted'].includes(ex.state)&&ex.segments?.length){const resume=document.createElement('button');resume.textContent='继续未完成片段';resume.onclick=async()=>{loading=true;controls();try{if(dirty)await save();const d=await api('resume-export',{id:job.id,export_id:ex.id});await load(d.id,d.version);}catch(e){fail(e);}finally{loading=false;controls();}};section.append(resume);}const links=document.createElement('div');links.className='links';for(const f of [...ex.files,{file:'manifest.json',title:'导出清单'}]){const a=document.createElement('a');a.textContent=f.title;a.href=`/concert-files/${job.id}/${ex.id}/${encodeURIComponent(f.file)}?download=1`;links.append(a);if(f.file!=='manifest.json'&&/\.(mp4|mkv|mov|webm|m4v)$/i.test(f.file)){const button=document.createElement('button');button.type='button';button.className='importKaraoke';button.textContent='导入卡拉 OK';button.title=`导入 ${f.title||f.file} 并切换到卡拉 OK 字幕`;button.onclick=()=>window.parent.postMessage({type:'lets-karaoke:import-concert-media',url:`/concert-files/${encodeURIComponent(job.id)}/${encodeURIComponent(ex.id)}/${encodeURIComponent(f.file)}`,name:f.file,size:f.size||0},location.origin);links.append(button);}}section.append(links);root.append(section);}}
function renderVersions(d){const select=$('version');select.replaceChildren();const versions=d.analysis_versions||[];if(!versions.length){const o=document.createElement('option');o.textContent='处理中';o.value='';select.append(o);select.disabled=true;renderSpeechReview();return;}select.disabled=false;for(const v of versions){const o=document.createElement('option');o.value=v.version;o.textContent=`v${v.version} · ${v.sensitivity} · ${v.candidates?.length||0} 个候选`;select.append(o);}select.value=String(d.selected_version||d.analysis_version||versions[versions.length-1].version);renderSpeechReview();}
function sameSource(a,b){return String(a||'').trim().replace(/^"|"$/g,'').replaceAll('/','\\').toLowerCase()===String(b||'').trim().replace(/^"|"$/g,'').replaceAll('/','\\').toLowerCase();}
function apply(d,replace){job=d;busy=['analyzing','exporting'].includes(d.state);$('status').textContent=d.message;$('progress').value=d.progress||0;$('videoTitle').textContent=d.name;$('duration').textContent=fmt(d.duration).split('.')[0];$('notice').textContent=d.notice||'正在生成声学候选边界，请等待分析完成。';$('source').value=d.source;$('minimum').value=d.min_length;$('sensitivity').value=d.sensitivity;$('analyze').textContent=d.id?'重新分析当前记录':'分析歌曲边界';$('reanalyze').hidden=true;renderVersions(d);$('reviewNotes').textContent=d.candidates?.length?`找到 ${d.candidates.length} 个声学候选边界；名称暂用片段编号。`:'没有足够明确的自动边界时，可在播放位置手动拆分。';
if(replace){rows=structuredClone(d.segments||[]);dirty=false;$('save').textContent='保存调整';renderRows();}const src=`/concert-files/${d.id}/source`;if($('player').getAttribute('src')!==src){$('player').src=src;auditionEnd=null;}const a=$('manifest');a.hidden=!rows.length;a.href=`/concert-files/${d.id}/concert.json?download=1`;a.textContent=dirty?'下载已保存时间表':'下载时间表';exportsUI();controls();draw();}
function schedule(){clearTimeout(timer);if(busy)timer=setTimeout(async()=>{try{const d=await api('job?id='+job.id+(job.selected_version?'&version='+job.selected_version:''));apply(d,!dirty);schedule();if(!busy)await history();}catch(e){fail(e);timer=setTimeout(schedule,2500);}},1200);}
async function load(id,version=null){if(dirty)await save();loading=true;controls();try{clearTimeout(timer);const d=await api('job?id='+encodeURIComponent(id)+(version?'&version='+encodeURIComponent(version):''));apply(d,true);localStorage.setItem('concert-job',d.id);schedule();}finally{loading=false;controls();}}
async function loadVersion(version){if(!job||!version||busy||loading)return;loading=true;controls();try{if(dirty)await save();const d=await api('job?id='+encodeURIComponent(job.id)+'&version='+encodeURIComponent(version));apply(d,true);}catch(e){renderVersions(job);fail(e);}finally{loading=false;controls();}}
async function history(){const jobs=await api('jobs');const root=$('history');root.replaceChildren();if(!jobs.length)root.textContent='还没有切割记录';for(const j of jobs){const item=document.createElement('div');item.className='historyItem';item.style.display='flex';item.style.gap='6px';const b=document.createElement('button');b.style.flex='1';b.textContent=j.name;const small=document.createElement('small');small.textContent=`${fmt(j.duration).split('.')[0]} · ${new Date(j.created*1000).toLocaleString()} · ${j.version_count||1} 个版本 · ${{ready:'待复核',done:'已导出',analyzing:'分析中',exporting:'导出中',error:'处理失败',cancelled:'已取消',interrupted:'已中断'}[j.state]||j.state}`;b.append(small);b.onclick=()=>load(j.id).catch(fail);const del=document.createElement('button');del.className='deleteHistory';del.style.color='#ff8f88';del.textContent='删除';del.title=`删除 ${j.name} 的全部版本和导出`;del.onclick=async()=>{if(!window.confirm(`确定删除“${j.name}”的全部版本和导出文件吗？`))return;try{await api('delete',{id:j.id});if(job?.id===j.id){job=null;rows=[];dirty=false;activeBoundary=null;clearTimeout(timer);$('manifest').hidden=true;$('downloads').replaceChildren();$('speechReview').hidden=true;draw();$('videoTitle').textContent='03 / 试听与复核';$('status').textContent='记录已删除';$('segments').replaceChildren();$('count').textContent='';$('player').removeAttribute('src');}await history();}catch(e){fail(e);}};item.append(b,del);root.append(item);}if(job&&!busy&&!dirty){const previous=job;const d=await api('job?id='+encodeURIComponent(previous.id)+(previous.selected_version?'&version='+encodeURIComponent(previous.selected_version):''));if(job===previous&&!busy&&!dirty){apply(d,true);localStorage.setItem('concert-job',d.id);}}controls();return jobs;}
async function save(){if(!job)return;const wasLoading=loading;loading=true;controls();try{$('error').textContent='';validate();const d=await api('save',{id:job.id,version:job.selected_version||job.analysis_version,revision:job.revision||0,segments:rows});apply(d,true);$('status').textContent='分段时间表已保存';}finally{loading=wasLoading;controls();}}
 async function analyze(forceNew=false){try{$('error').textContent='';const source=$('source').value;const options={min_length:Number($('minimum').value),sensitivity:$('sensitivity').value};if(dirty)await save();loading=true;controls();const existing=!forceNew&&job&&sameSource(source,job.source);const d=existing?await api('reanalyze',{id:job.id,version:job.selected_version||job.analysis_version,...options}):await api('analyze',{source,...options});dirty=false;await load(d.id);await history();}catch(e){fail(e);}finally{loading=false;controls();}};
$('analyze').onclick=()=>analyze();$('newAnalysis').onclick=()=>analyze(true);
$('reanalyze').onclick=async()=>{try{$('error').textContent='';if(!job)throw Error('请先点击一条切割记录');if(dirty)await save();loading=true;controls();const d=await api('reanalyze',{id:job.id,version:job.selected_version||job.analysis_version,min_length:Number($('minimum').value),sensitivity:$('sensitivity').value});dirty=false;await load(d.id);await history();}catch(e){fail(e);}finally{loading=false;controls();}};
$('version').onchange=()=>loadVersion($('version').value);
$('save').onclick=()=>save().catch(fail);
$('export').onclick=async()=>{try{$('error').textContent='';validate();if(!rows.some(s=>s.selected))throw Error('请至少选中一个片段');loading=true;controls();const d=await api('export',{id:job.id,version:job.selected_version||job.analysis_version,revision:job.revision||0,segments:rows,mode:$('mode').value});dirty=false;await load(d.id,d.version);}catch(e){fail(e);}finally{loading=false;controls();}};
$('cancel').onclick=()=>api('cancel',{id:job.id}).then(()=>{$('status').textContent='正在停止处理…';}).catch(fail);
$('refresh').onclick=()=>history().catch(fail);
$('back').onclick=()=>seek($('player').currentTime-5);$('forward').onclick=()=>seek($('player').currentTime+5);
$('split').onclick=()=>{const t=Math.round($('player').currentTime*1000)/1000,i=rows.findIndex(s=>t>s.start+.2&&t<s.end-.2);if(i<0)return fail(Error('请将播放位置移到片段内部'));const s=rows[i];rows.splice(i+1,0,{...s,start:t,title:s.title+'（续）'});s.end=t;mark();renderRows();};
$('snap').onclick=()=>snapCurrentBoundary();
$('merge').onclick=()=>mergeCurrentBoundary();
$('waveform').tabIndex=0;
$('waveform').addEventListener('pointerdown',e=>{if(!job||busy||loading)return;$('waveform').focus();const hit=boundaryAt(e.clientX);if(hit!==null){activeBoundary=hit;draggingBoundary=true;$('waveform').setPointerCapture?.(e.pointerId);e.preventDefault();draw();}else seek(canvasTime(e));});
$('waveform').addEventListener('pointermove',e=>{if(draggingBoundary&&!busy&&!loading)setBoundary(activeBoundary,canvasTime(e));});
$('waveform').addEventListener('pointerup',e=>{if(draggingBoundary){draggingBoundary=false;$('waveform').releasePointerCapture?.(e.pointerId);}});
$('waveform').addEventListener('pointercancel',()=>{draggingBoundary=false;});
$('waveform').addEventListener('dblclick',e=>{if(busy||loading)return;const hit=boundaryAt(e.clientX);if(hit!==null)mergeBoundary(hit);});
$('waveform').addEventListener('keydown',e=>{if(busy||loading)return;if((e.key==='Delete'||e.key==='Backspace')&&activeBoundary!==null){e.preventDefault();mergeBoundary(activeBoundary);}});
$('player').addEventListener('timeupdate',()=>{$('playTime').textContent=fmt($('player').currentTime);if(auditionEnd!==null&&$('player').currentTime>=auditionEnd){$('player').pause();auditionEnd=null;}draw();});
$('mode').onchange=()=>{$('modeHelp').textContent=$('mode').value==='copy'?'快速模式不重新压缩，速度快；受视频关键帧限制，开头可能包含切点前的画面。':'精确模式使用 H.264 重新编码，保留指定起止时间，整场导出耗时较长。建议先选一段检查。';};
$('player').addEventListener('error',()=>{if(job)fail(Error($('player').error?.code===4?'浏览器无法播放此编码。仍可分析和导出；请用外部播放器试听，或精确导出为兼容 MP4。':'视频读取失败，请确认原视频仍存在且没有被移动或替换。'));});
window.addEventListener('resize',draw);window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
history().then(async jobs=>{const stored=localStorage.getItem('concert-job'),id=jobs.find(j=>j.id===stored)?.id||jobs[0]?.id;if(id)await load(id);}).catch(fail);controls();
})();
